
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-18T09:23:56-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c1442caa2369936d2ba7e2eebd2d975d6f4787d",
 "version": "0.3.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
