[tool.poetry]
name = "circleso"
version = "0.1.0.dev0"
description = "Implementation of Circles in Python"
authors = ["Calico Niko"]
license = "GPL-3.0"
packages = [
    {include = "circles"}
]

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
opencv-python = "^4.5.5"
numpy = "^1.22.3"
scipy = "^1.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
