[tool.poetry]
name = "ThingsMatrix"
version = "0.7.0"
description = ""
authors = ["yooooyo <loipswqe@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.0"
requests = "^2.27.1"
rich = "^12.0.1"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pre-commit = "^2.17.0"
ipython = "^8.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
thingsmatrix = 'thingsmatrix.main:run'
