
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T13:26:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "83de7d2b63f5ff7a07b24b61e073f14cdc321656",
 "version": "0.2.0.post0.dev75"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
