
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T14:33:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1291bafa98653a807fcffbe7d02e968c20162c51",
 "version": "0.2.0.post0.dev83"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
