# THIS FILE IS GENERATED BY SETUP.PY
# DO NOT MODIFY BY HAND
version = '2.3.0'
git_version = '9d0e0b5aa08a9da7770aa49537b712f007267903'
full_version = '2.3.0'
is_release = True

if not is_release:
    version = full_version