[tool.poetry]
name = "sph"
version = "0.1.0"
description = ""
authors = ["François Poizat <francois.poizat@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
pylama = "^8.3.8"
setuptools = "^62.1.0"
GitPython = "^3.1.27"
colorama = "^0.4.4"
pylint = "^2.13.8"
halo = "^0.0.31"
xdg = "^5.1.1"
PyGithub = "^1.55"
PyYAML = "^6.0"
flake8 = "^4.0.1"
bandit = "^1.7.4"

[tool.poetry.dev-dependencies]
jedi = "^0.18.1"

[tool.poetry.scripts]
sph = "sph:be_helpful"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
