[tool.poetry]
name = "pip-compile-cross-platform"
version = "0.9.3"
description = "Lock your dependencies once, use your lockfile everywhere"
authors = ["Mitchell Hentges <mitch9654@gmail.com>"]
readme = "README.md"
packages = [{include = "pip_compile_cross_platform"}]
repository = "https://gitlab.com/mitchhentges/pip-compile-cross-platform"
license = "AGPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.7"
poetry = "^1.2.0b1"
pip-requirements-parser = "^31.2.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pyupgrade = "^2.32"
flake8 = "^4.0"
mypy = "^0.950"

[tool.poetry.scripts]
pip-compile-cross-platform = "pip_compile_cross_platform:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
