[build-system]
requires = ["setuptools", "wheel", "cmake<3.20"]

[tool.black]
experimental-string-processing = true
line-length = 79
include = '\.pyi?|bin/*$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''


