
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T17:07:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "82ca03e9814d01e6a995b98e88da81d555c77056",
 "version": "0.15.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
