
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-23T09:55:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc80b83357606ae5d8346689797adacf5f673a15",
 "version": "2672"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
