[tool.poetry]
name = "nops-kafka"
version = "0.2.0"
description = "Kafka tooling used in nOps.io"
authors = ["nOps Engineers <eng@nops.io>"]

[tool.poetry.dependencies]
kafka_python = ">2.0.0"
msgpack = ">1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py39']

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
force_single_line = true
default_section = 'THIRDPARTY'
known_django = 'django'
sections = 'FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
