[tool.poetry]
name = "arcane-ga4"
version = "0.1.0"
description = "Utility functions for ga4 api call"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.7"
google-analytics-admin = "0.8.1"
google-api-core = "2.8.0"
google-auth = "2.6.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
