
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-17T00:51:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "58a2216e90148524b0131c94b0497f895cc17aae",
 "version": "0.2.0.post0.dev63"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
