[tool.poetry]
name = "pythogen"
version = "0.0.6"
description = ""
authors = []

[tool.poetry.dependencies]
python = "3.9.*"
typer = "0.4.1"
pyyaml = "6.0"
jinja2 = "3.1.1"
rich = "12.2.0"
inflection = "0.5.1"

[tool.poetry.scripts]
poetry = 'pythogen.entrypoint'

[build-system]
requires = ["poetry>=1.1.0"]
build-backend = "poetry.masonry.api"
