ROUTE_PREFIX = "/api/v1"
ANALYZER_DASHBOARD = "/analyzer"
ANALYZER_PREFIX = ROUTE_PREFIX + ANALYZER_DASHBOARD
CHEMISTRY_PREFIX = ROUTE_PREFIX + "/chemistry"
EXECUTE_PREFIX = ROUTE_PREFIX + "/execute"
COMBINATORIAL_OPTIMIZATION_PREFIX = ROUTE_PREFIX + "/combinatorial_optimization"
QSVM_PREFIX = ROUTE_PREFIX + "/qsvm"

ANALYZER_FE_APP = "https://analyzer.classiquantum.com/"
ANALYZER_BE_APP = "https://api-analyzer.classiquantum.com/"
UPLOAD_ANALYZER = "api/python_upload"
ANALYZER_UPLOAD_FULL_PATH = ANALYZER_BE_APP + UPLOAD_ANALYZER

TASKS_SUFFIX = "/tasks"
RB = "/rb"
ASYNC_TASKS_SUFFIX = "/async_tasks"
TASKS_GENERATE_SUFFIX = TASKS_SUFFIX + "/generate"
TASKS_SOLVE_SUFFIX = "/tasks/solve"
TASKS_SOLVE_ASYNC_SUFFIX = "/tasks/solve_async"
TASKS_WS_SOLVE_SUFFIX = "/ws/tasks/solve"
TASKS_SOLVE_CLASSICALLY_SUFFIX = "/tasks/solve_classically"
TASKS_OPERATOR_SUFFIX = "/tasks/operator"
TASKS_OBJECTIVE_SUFFIX = "/tasks/objective"
TASKS_INITIAL_POINT_SUFFIX = "/tasks/initial_point"
TASK_TRAIN_SUFFIX = TASKS_SUFFIX + "/train"
TASK_TEST_SUFFIX = TASKS_SUFFIX + "/test"
TASK_PREDICT_SUFFIX = TASKS_SUFFIX + "/predict"
TASK_RB_SUFFIX = TASKS_SUFFIX + RB
TASKS_GENERATE_FULL_PATH = ROUTE_PREFIX + TASKS_GENERATE_SUFFIX
TASKS_SOLVE_EXACT_SUFFIX = "/tasks/solve_exact"

EXECUTE_TASKS_FULL_PATH = EXECUTE_PREFIX + TASKS_SUFFIX
EXECUTE_ASYNC_TASKS_FULL_PATH = EXECUTE_PREFIX + ASYNC_TASKS_SUFFIX

ANALYZER_FULL_PATH = ANALYZER_PREFIX + TASKS_SUFFIX
ANALYZER_RB_FULL_PATH = ANALYZER_PREFIX + TASK_RB_SUFFIX
COMBINATORIAL_OPTIMIZATION_GENERATE_FULL_PATH = (
    COMBINATORIAL_OPTIMIZATION_PREFIX + TASKS_GENERATE_SUFFIX
)
COMBINATORIAL_OPTIMIZATION_SOLVE_FULL_PATH = (
    COMBINATORIAL_OPTIMIZATION_PREFIX + TASKS_SOLVE_SUFFIX
)
COMBINATORIAL_OPTIMIZATION_WS_SOLVE_FULL_PATH = (
    COMBINATORIAL_OPTIMIZATION_PREFIX + TASKS_WS_SOLVE_SUFFIX
)
COMBINATORIAL_OPTIMIZATION_SOLVE_ASYNC_FULL_PATH = (
    COMBINATORIAL_OPTIMIZATION_PREFIX + TASKS_SOLVE_ASYNC_SUFFIX
)
COMBINATORIAL_OPTIMIZATION_SOLVE_CLASSICALLY_FULL_PATH = (
    COMBINATORIAL_OPTIMIZATION_PREFIX + TASKS_SOLVE_CLASSICALLY_SUFFIX
)
COMBINATORIAL_OPTIMIZATION_OPERATOR_FULL_PATH = (
    COMBINATORIAL_OPTIMIZATION_PREFIX + TASKS_OPERATOR_SUFFIX
)
COMBINATORIAL_OPTIMIZATION_OBJECTIVE_FULL_PATH = (
    COMBINATORIAL_OPTIMIZATION_PREFIX + TASKS_OBJECTIVE_SUFFIX
)
COMBINATORIAL_OPTIMIZATION_INITIAL_POINT_FULL_PATH = (
    COMBINATORIAL_OPTIMIZATION_PREFIX + TASKS_INITIAL_POINT_SUFFIX
)

CHEMISTRY_GENERATE_HAMILTONIAN_FULL_PATH = CHEMISTRY_PREFIX + TASKS_SUFFIX
CHEMISTRY_SOLVE_EXACT_FULL_PATH = CHEMISTRY_PREFIX + TASKS_SOLVE_EXACT_SUFFIX
CHEMISTRY_SOLVE_FULL_PATH = CHEMISTRY_PREFIX + TASKS_SOLVE_SUFFIX

QSVM_TRAIN = QSVM_PREFIX + TASK_TRAIN_SUFFIX
QSVM_TEST = QSVM_PREFIX + TASK_TEST_SUFFIX
QSVM_PREDICT = QSVM_PREFIX + TASK_PREDICT_SUFFIX
