name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install Dependencies
        run: pip install -e .[doc]

      - name: Generate Docs
        run: pdoc -d numpy auth0_jwt_validator/ -o docs/
