[tool.poetry]
name = "paper_neural"
version = "0.2.4"
description = "Reunir mecanimos de detecção de fibras de segurança e comparação de features"
authors = ["wagner <rengaw.luiz@gmail.com>"]
packages = [
    { include = "paper_neural" },
    { include = "siamese" }
]

[tool.poetry.dependencies]
python = "^3.9"
torch  = "^1.8.2+cu111"
numpy = "^1.22.3"
Pillow = "^9.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
