
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-22T21:02:12-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b8a7dd230f724490dbf4ebf9f59ab863283a2ec",
 "version": "1.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
