
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T10:07:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe1a0be3547a57b9f8f24aeb108c81f0f8e84334",
 "version": "0.1.0a61"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
