
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-17T17:22:21-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "104dc0379c3585a0bc8ebb87f61f2ae38d101b83",
 "version": "2.6.6.dev20220519"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
