[tool.poetry]
name = "python-magic"
version = "0.4.26"
description = "python-magic is a Python interface to the libmagic file type"
authors = ["identification libra"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
