# Generated by Django 3.2.5 on 2021-10-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('comment', models.TextField()),
                ('definition', models.TextField()),
                ('synonyms', models.JSONField()),
                ('xrefs', models.JSONField()),
                ('is_a', models.ManyToManyField(to='hpo.Phenotype')),
            ],
        ),
    ]
