# Generated by Django 3.2.5 on 2021-10-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenotype',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
