# Generated by Django 3.2.5 on 2021-10-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpo', '0002_auto_20211021_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenotype',
            name='synonyms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='xrefs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
