# Generated by Django 4.0.4 on 2022-05-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hpo', '0003_auto_20211021_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenotype',
            name='top_parent',
            field=models.ForeignKey(default='HP:0000001', on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='hpo.phenotype'),
            preserve_default=False,
        ),
    ]
