
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-23T14:34:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0005b5a16d46353a6d4fda2da9c56b979578a08",
 "version": "0.7.124"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
