
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: envoy.base.utils:package

from setuptools import setup

setup(**{
    'author': 'Ryan Northey',
    'author_email': 'ryan@synca.io',
    'description': '"A collection of utils used in Envoy proxy\'s CI"',
    'entry_points': {
        'console_scripts': [
            'envoy.project=envoy.base.utils:project_cmd',
        ],
    },
    'install_requires': (
        'abstracts>=0.0.12',
        'aio.api.github>=0.1.1',
        'aio.core>=0.8.2',
        'aio.run.runner>=0.3.2',
        'aiohttp',
        'frozendict',
        'jinja2',
        'packaging',
        'pytz',
        'pyyaml',
        'trycast>=0.7.3',
    ),
    'license': 'Apache Software License 2.0',
    'long_description': """
envoy.base.utils
================

Base utilities for Envoy proxy's CI
""",
    'maintainer': 'Ryan Northey',
    'maintainer_email': 'ryan@synca.io',
    'name': 'envoy.base.utils',
    'namespace_packages': (
    ),
    'package_data': {
        'envoy.base.utils': (
            'py.typed',
        ),
    },
    'packages': (
        'envoy.base.utils',
        'envoy.base.utils.abstract',
        'envoy.base.utils.abstract.project',
    ),
    'url': 'https://github.com/envoyproxy/pytooling/tree/main/envoy.base.utils',
    'version': '0.2.7',
})
