# coding: utf-8

"""
    Investor8.Core

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CurrentMetricsDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'symbol': 'str',
        'metric': 'str',
        'value': 'str'
    }

    attribute_map = {
        'symbol': 'Symbol',
        'metric': 'Metric',
        'value': 'Value'
    }

    def __init__(self, symbol=None, metric=None, value=None):  # noqa: E501
        """CurrentMetricsDto - a model defined in Swagger"""  # noqa: E501
        self._symbol = None
        self._metric = None
        self._value = None
        self.discriminator = None
        if symbol is not None:
            self.symbol = symbol
        if metric is not None:
            self.metric = metric
        if value is not None:
            self.value = value

    @property
    def symbol(self):
        """Gets the symbol of this CurrentMetricsDto.  # noqa: E501


        :return: The symbol of this CurrentMetricsDto.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this CurrentMetricsDto.


        :param symbol: The symbol of this CurrentMetricsDto.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def metric(self):
        """Gets the metric of this CurrentMetricsDto.  # noqa: E501


        :return: The metric of this CurrentMetricsDto.  # noqa: E501
        :rtype: str
        """
        return self._metric

    @metric.setter
    def metric(self, metric):
        """Sets the metric of this CurrentMetricsDto.


        :param metric: The metric of this CurrentMetricsDto.  # noqa: E501
        :type: str
        """

        self._metric = metric

    @property
    def value(self):
        """Gets the value of this CurrentMetricsDto.  # noqa: E501


        :return: The value of this CurrentMetricsDto.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this CurrentMetricsDto.


        :param value: The value of this CurrentMetricsDto.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CurrentMetricsDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CurrentMetricsDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
