# Autogenerated file, do not edit!
__version__ = '1.11.200'
__gitrev__ = 'c7fa838368889da6a7da47de1b9cd116cf707cd1'
__avx_version__ = 'AVX2'
__torch_gitrev__ = 'c85c97669c25c7aed0728d0762c0ce1c88188316'
__mode__ = 'release'
