MORSE_CODE_DICT = {'A': '.-',
                   'B': '-...',
                   'C': '-.-.',
                   'D': '-..',
                   'E': '.',
                   'F': '..-.',
                   'G': '--.',
                   'H': '....',
                   'I': '..',
                   'J': '.---',
                   'K': '-.-',
                   'L': '.-..',
                   'M': '--',
                   'N': '-.',
                   'O': '---',
                   'P': '.--.',
                   'Q': '--.-',
                   'R': '.-.',
                   'S': '...',
                   'T': '-',
                   'U': '..-',
                   'V': '...-',
                   'W': '.--',
                   'X': '-..-',
                   'Y': '-.--',
                   'Z': '--..',
                   '1': '.----',
                   '2': '..---',
                   '3': '...--',
                   '4': '....-',
                   '5': '.....',
                   '6': '-....',
                   '7': '--...',
                   '8': '---..',
                   '9': '----.',
                   '0': '-----',
                   ', ': '--..--',
                   '.': '.-.-.-',
                   '?': '..--..',
                   '/': '-..-.',
                   '-': '-....-',
                   '(': '-.--.',
                   ')': '-.--.-'
}

ANIMALS_FACTS = [
    {"question": "What is the name of the fastest land animal?", "answer": "Cheetah"},
    {"question": "What’s the only mammal that’s able to fly?", "answer": "Bat"},
    {"question": "What’s a group of kittens called?", "answer": "Kindle"},
    {"question": "What are the horns of a rhinoceros made of?", "answer": "Hair"},
    {"question": "What name is given to a female deer?", "answer": "Doe"},
    {"question": "What animal is known by the nickname “sea cow?”", "answer": "Manatees"},
    {"question": "What animal is said to have 9 lives?", "answer": "Cat"},
    {"question": "What is the only mammals that can’t jump?", "answer": "Elephant"},
    {"question": "What animal eats mainly bamboo?", "answer": "Panda"},
    {"question": "Which animal can stand on its tail?", "answer": "Kangaroo"},
    {"question": "Which animal is the tallest in the world?", "answer": "Giraffe"},
    {"question": "What animal is covered in quills?", "answer": "Porcupine"}
]

HISTORY_FACTS = [
    {"question": "One of the ancient world wonders, the Hanging Gardens, was found in which city?", "answer": "Babylon"},
    {"question": "Greenland was a colony of which country until 1981?", "answer": "Denmark"},
    {"question": "How many days in a week were there in ancient Roman times?", "answer": "8"},
    {"question": "How many days was William Harrison President of the United States?", "answer": "32"},
    {"question": "What was the family name of the Russian rulers from the 17th century until the 1917 revolution?", "answer": "Romanov"},
    {"question": "How many U.S. presidents have been assassinated?", "answer": "4"},
    {"question": "When did Mao Zedong come to power?", "answer": "1949"},
    {"question": "In which country did the Easter Rising take place in 1916?", "answer": "Ireland"},
    {"question": "Which Greek historian is known as the Father of History?", "answer": "Herodotus"},
    {"question": "The Ptolemy dynasty ruled which ancient kingdom?", "answer": "Egypt"},
    {"question": "The ancient city of Rome was built on how many hills?", "answer": "7"},
    {"question": "The Peloponnesian War was fought between Athens and which other ancient Greek state?", "answer": "Sparta"},
    {"question": "What is the name of the first human civilization?", "answer": "Mesopotamia"}
]