# Autogenerated file, do not edit!
__version__ = '1.11.200'
__gitrev__ = 'c7fa838368889da6a7da47de1b9cd116cf707cd1'
__avx_version__ = 'AVX2'
__torch_gitrev__ = 'b809f1a38fe15fc1b6ab307597aff9f5944f4bc5'
__mode__ = 'release'
