
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T15:45:44+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "99e19ec180b518fc61e4d7e01315f4bc83c92034",
 "version": "0.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
