[tool.poetry]
name = "peachpayments-partner-pydantic"
version = "0.2.5"
description = "PeachPayments Partner Pydantic library contains Pydantic schemas to help integrate PeachPayments with their partners."
readme = "README.md"
license = "MIT"
authors = ["PeachPayments <support@peachpayments.com>"]
repository = "https://gitlab.com/peachpayments/peachpayments-partner-pydantic/"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: Financial and Insurance Industry",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Utilities",
  "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.8.2"
iso4217 = "^1.6.20180829"
email-validator = "^1.1.3"
ipaddress = "^1.0.23"
peachpayments-partner = "0.1.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.3.0"
mypy = "0.942"
flake8 = "^4.0.1"
autoflake = "^1.4"
isort = "^5.10.1"
pytest-cov = "^3.0.0"
pytest-mypy = "^0.8.1"
pydocstyle = "^6.1.1"
pre-commit = "^2.15.0"
ipaddress = "^1.0.23"
python-dateutil = "^2.8.2"
types-python-dateutil = "^2.8.3"
mock = "^4.0.3"
types-mock = "^4.0.4"
freezegun = "^1.1.0"
pytest-asyncio = "^0.16.0"
types-freezegun = "^1.1.6"
datamodel-code-generator = "^0.11.19"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py39"]

[tool.mypy]
ignore_missing_imports=true
