
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-16T16:14:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a96c75cf3b3eeecf4f7979a5415df86943ad1c1",
 "version": "2.4.3dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
