image: registry.gitlab.com/materials-modeling/calorine/cicd

variables:
  INSTDIR_LINUX: "local_installation_linux"

before_script:
  - export PYTHONPATH=$PWD/$INSTDIR_LINUX:${PYTHONPATH}

#------------------- build stage -------------------

build:linux:
  stage: build
  script:
    - pip3 install --target=$INSTDIR_LINUX .
  artifacts:
    expire_in: 2 days
    paths:
      - local_installation_linux/
  tags:
    - linux

#------------------- test stage -------------------

style_check:
  stage: test
  tags:
    - linux
  script:
    - flake8 calorine/ tests/ doc/

standard_tests:
  stage: test
  needs:
    - build:linux
  tags:
    - linux
  script:
    #- xdoctest calorine   # commented out until we have fixed the doctests
    - coverage run -m pytest --verbose --junitxml=report.xml tests/
    - coverage report -m
    - coverage html
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    expire_in: 2 days
    paths:
      - htmlcov/
    reports:
      junit: report.xml

test_documentation:
  stage: test
  tags:
    - linux
  needs:
    - build:linux
  except:
    - master
  artifacts:
    expire_in: 1 days
    paths:
      - public
  script:
    - sphinx-build -W doc/ public/
    - ls -l public/

#------------------- deploy stage -------------------

pages:
  stage: deploy
  tags:
    - linux
  script:
    - sphinx-build -W doc/ public/
    - ls -l public/
    - cp -dr htmlcov/ public/coverage/
    - chmod go-rwX -R public/
  artifacts:
    expire_in: 2 days
    paths:
      - public
  only:
    - master

pypi:
  stage: deploy
  tags:
    - linux
  only:
    - tags
  except:
    - schedules
  when: manual
  environment:
      name: pypi-upload
  script:
    # check out the latest tag (redundant if job is limited to tags; still a sensible precaution)
    - tag=$(git tag | tail -1)
    - echo "tag= $tag"
    - git checkout $tag
    # create source distribution and push to PyPI
    - python3 setup.py sdist
    - ls -l dist/
    - python3 -m twine upload dist/*
