
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-23T10:53:22+0430",
 "dirty": false,
 "error": null,
 "full-revisionid": "08d4b84c3f1429c676c029e80b622f975a2c44c0",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
