# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.main_layout = QtWidgets.QVBoxLayout(self.central_widget)
        self.main_layout.setObjectName("main_layout")
        self.sudoku_grid = SudokuWidget(self.central_widget)
        self.sudoku_grid.setObjectName("sudoku_grid")
        self.main_layout.addWidget(self.sudoku_grid)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.solve_button = QtWidgets.QPushButton(self.central_widget)
        icon = QtGui.QIcon.fromTheme("system-run")
        self.solve_button.setIcon(icon)
        self.solve_button.setDefault(True)
        self.solve_button.setObjectName("solve_button")
        self.button_layout.addWidget(self.solve_button)
        self.clear_button = QtWidgets.QPushButton(self.central_widget)
        icon = QtGui.QIcon.fromTheme("edit-clear")
        self.clear_button.setIcon(icon)
        self.clear_button.setObjectName("clear_button")
        self.button_layout.addWidget(self.clear_button)
        self.main_layout.addLayout(self.button_layout)
        MainWindow.setCentralWidget(self.central_widget)
        self.tool_bar = QtWidgets.QToolBar(MainWindow)
        self.tool_bar.setMovable(False)
        self.tool_bar.setIconSize(QtCore.QSize(32, 32))
        self.tool_bar.setObjectName("tool_bar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tool_bar)
        self.status_bar = QtWidgets.QStatusBar(MainWindow)
        self.status_bar.setObjectName("status_bar")
        MainWindow.setStatusBar(self.status_bar)
        self.quit_action = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.quit_action.setIcon(icon)
        self.quit_action.setShortcut("Ctrl+Q")
        self.quit_action.setObjectName("quit_action")
        self.about_action = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("help-about")
        self.about_action.setIcon(icon)
        self.about_action.setObjectName("about_action")
        self.tool_bar.addAction(self.quit_action)
        self.tool_bar.addAction(self.about_action)

        self.retranslateUi(MainWindow)
        self.quit_action.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sudoku"))
        self.solve_button.setText(_translate("MainWindow", "Résoudre"))
        self.clear_button.setText(_translate("MainWindow", "Réinitialiser"))
        self.tool_bar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.quit_action.setText(_translate("MainWindow", "Quitter"))
        self.quit_action.setToolTip(_translate("MainWindow", "Quitter l\'application"))
        self.about_action.setText(_translate("MainWindow", "À propos"))
        self.about_action.setToolTip(_translate("MainWindow", "Afficher quelques informations utiles"))
from sudoku.gui.SudokuWidget import SudokuWidget
