[tool.poetry]
name = "externalpyoverlay"
version = "1.0.3"
description = ""
authors = ["Xenely <a.maryatkin14@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
