[tool.poetry]
name = "ceplib"
version = "0.1.2"
description = "An easy way to fetch Brazil Zip code using several services"
authors = ["Erick Duarte <erickod@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/erickod/CepLib"
repository = "https://github.com/erickod/CepLib"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.22.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
