
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-18T17:12:38+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8fb6ca4ab255d25e00558340d1c5bd23ae236b22",
 "version": "0.15.6a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
