[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "aasm"
author = "unknown"
home-page = "https://github.com/agent-based-information-flow-simulation/agents-assembly-translator"
description-file = "README.md"

