
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T21:42:17-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2a7bfa59d4a2524d72e51492bdeef101ae3f03b",
 "version": "2.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
