# Generated by Django 3.2.13 on 2022-05-16 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import mixins.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', mixins.fields.AutoDateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Set this to prioritise the order of the icon, higher numbers are shown first.')),
                ('is_enabled', models.BooleanField(default=False, help_text='Check this if you would like this icon to be displayed.')),
                ('icon', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'ordering': ['-order', 'name', '-created_at'],
            },
        ),
    ]
