[tool.poetry]
name = "peachpayments-partner"
version = "0.1.8"
description = "PeachPayments Partner Library is a platform agnostic Python package to help integrating PeachPayments with their partners."
readme = "README.md"
license = "MIT"
authors = ["PeachPayments <support@peachpayments.com>"]
repository = "https://gitlab.com/peachpayments/peach-partner-python/"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: Financial and Insurance Industry",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Utilities",
  "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.9"
iso4217 = "^1.6.20180829"
requests = "^2.26.0"
cryptography = "^36.0.0"
PyJWT = "^2.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.942"
flake8 = "^3.9.2"
autoflake = "^1.4"
black = "^22.3.0"
isort = "^5.9.1"
pytest-cov = "^2.12.1"
pytest-mypy = "^0.8.1"
pydocstyle = "^6.1.1"
freezegun = "^1.1.0"
types-freezegun = "^1.1.0"
pre-commit = "^2.15.0"
mock = "^4.0.3"
types-mock = "^4.0.1"
types-requests = "^2.25.6"
Sphinx = "4.2.0"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py39"]

[tool.mypy]
ignore_missing_imports = true
