[tool.poetry]
name = "aliby-agora"
version = "0.2.26"
description = "A gathering of shared utilities for the Swain Lab image processing pipeline."
authors = ["Julian Pietsch <jpietsch@ed.ac.uk>", "Alán Muñoz <amuoz@ed.ac.uk>"]
license = "MIT"
packages = [
    { include = "agora" },
    { include = "logfile_parser" },
]

[tool.poetry.dependencies]
python = "^3.7.1,<3.11"
PyYAML = "^6.0"
py-find-1st = "^1.1.5"
h5py = "2.10"
pandas = "^1.1.4"
opencv-python = "*"
numpy = ">=1.6.0"
scipy = ">=1.7.3"

[tool.poetry.dev-dependencies]
data-science-types = "^0.2.23"
black = "^21.12b0"
Sphinx = "^4.3.2"
pytest = "^6.2.5"
mypy = "^0.930"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
