[project]
name = "download-torch-pkm-repo"
version = "0.1.0"
description = "light-the-torch based repository for pkm"
readme = "README.md"
requires-python= ">=3.8, <4.0"
authors = [{name="bennyl"}]
dependencies = [ "pkm >=0.4.22, <1"]

[project.entry-points.pkm-repositories]
torch= "download_torch_pkm_repo.pkm_extension:install"

[build-system]
requires=["pkm"]
build-backend = "pkm.api.buildsys"