
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-18T14:52:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "fbb566f2d088b2a0b97b41babe1abb7e3b715f16",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
