[project]
name = "ista"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[tool.poetry]
name = "istars"
version = "0.0.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
ista = { file = "./target/wheels/ista-0.1.0-cp38-cp38-manylinux_2_28_x86_64.whl" }


[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"
