[tool.poetry]
name = "pyinaturalist-convert"
version = "0.3.0"
description = "Convert iNaturalist observation data to and from multiple formats"
authors = ["Jordan Cook"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/JWCook/pyinaturalist_convert"
repository = "https://github.com/JWCook/pyinaturalist_convert"
documentation = "https://pyinaturalist.readthedocs.io"
keywords = ["inaturalist", "biodiversity", "export", "convert", "csv", "darwin-core", "dataframe", "gpx"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Typing :: Typed",
]
include = [
    { path = "*.md", format = "sdist"  },
    { path = "*.yml", format = "sdist"  },
    { path = "docs", format = "sdist" },
    { path = "examples", format = "sdist" },
    { path = "test", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.8"
geojson = ">=2.5"
pyinaturalist = ">=0.17.0"
flatten-dict = "^0.4.0"
tablib = "^3.0"
tabulate = "^0.8.9"

# Optional dependencies for specific data formats
boto3 = {version = ">=1.20", optional = true}
gpxpy = {version = "^1.4.2", optional = true}
openpyxl = {version = ">=2.6", optional = true}
pandas = {version = ">=1.2", optional = true}
pyarrow = {version = ">=4.0", optional = true}
python-dwca-reader = {version = "^0.15.0", optional = true}
xmltodict = {version = ">=0.12", optional = true}
tables = {version = ">=3.6", optional = true}

# Documentation dependencies
furo                        = {optional=true, version="^2022.2.14.1"}
myst-parser                 = {optional=true, version="^0.17.0"}
sphinx                      = {optional=true, version="^4.2.0"}
sphinx-autodoc-typehints    = {optional=true, version="^1.17"}
sphinx-copybutton           = {optional=true, version=">=0.5"}
sphinx-inline-tabs          = {optional=true, version="^2022.1.2b11"}
sphinx-panels               = {optional=true, version="^0.6.0"}
sphinxcontrib-apidoc        = {optional=true, version="^0.3"}

[tool.poetry.extras]
csv        = ["pandas"]
df         = ["pandas"]
dwc        = ["xmltodict"]
feather    = ["pandas", "pyarrow"]
gpx        = ["gpxpy"]
hdf        = ["pandas", "tables"]
html       = ["jinja", "tablib[html]"]
odp        = ["boto3"]
parquet    = ["pandas", "pyarrow"]
xlsx       = ["openpyxl"]

all = ["boto3", "gpxpy", "openpyxl", "pandas", "pyarrow", "python-dwca-reader",
       "tablib[all]", "xmltodict"]
docs = ["furo", "myst-parser", "sphinx", "sphinx-autodoc-typehints", "sphinx-copybutton",
        "sphinx-inline-tabs", "sphinx-panels", "sphinxcontrib-apidoc"]


[tool.poetry.dev-dependencies]
coverage = ">=6.3"
nox = "^2022.1.7"
nox-poetry = "^0.9.0"
pre-commit = "^2.18"
pyparsing = "^3.0"
pytest = ">=7.0"
pytest-cov = ">=3.0"
pytest-xdist = ">=2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization = true
line-length = 100

[tool.coverage.html]
directory = 'test-reports'

[tool.coverage.run]
branch = true
source = ['pyinaturalist_convert']

[tool.isort]
profile = 'black'
line_length = 100
skip_gitignore = true
skip = ['pyinaturalist_convert/__init__.py']
known_first_party = ['test']

[tool.mypy]
ignore_missing_imports = true
files = ['pyinaturalist_convert']
