
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T14:10:14-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "17de6b9886f240e07639eadea67b824b077f9501",
 "version": "3.1.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
