apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: nowapi
spec:
  selector:
    app: now-frontend
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
