
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T18:08:53-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe06f0f8807417e2323bf84f4d6e0949b2a1f937",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
