
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-12T22:55:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e2e2366850664544030c1fd769d6b6d25b9d9bba",
 "version": "2.6.6.dev20220517"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
