# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '0.9.6rc'
git_version = 'f77b7c6db44f2bbd7ee9ee939954d139daa9d67b'
