
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T22:21:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "14b1149d9f13e56b8f616607122413167f2798e4",
 "version": "0.1.1a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
