
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T15:48:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "298d0fe0734d191b1006a047ac8df433e0ec6b67",
 "version": "0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
