[tool.poetry]
authors = ["Didier SCHMITT <dschmitt@equancy.com>"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
]
description = "Datalake Catalog"
license = "MIT"
name = "datalake-catalog"
readme = "README.md"
repository = "https://github.com/equancy/datalake-catalog"
version = "1.0.4"

[tool.poetry.dependencies]
Flask = "^2.1.2"
Flask-JWT-Extended = "^4.4.0"
PyMySQL = {version = "^1.0.2", optional = true}
click = "^8.1.3"
gunicorn = "^20.1.0"
jsonschema = "^4.5.1"
pony = "0.7.16"
psycopg2-binary = {version = "^2.9.3", optional = true}
python = "^3.8"

[tool.poetry.extras]
all = ["PyMySQL", "psycopg2-binary"]
mysql = ["PyMySQL"]
pgsql = ["psycopg2-binary"]

[tool.poetry.dev-dependencies]
black = "^22.3.0"
coverage = "^6.3.3"
flake9 = "^3.8.3"
pytest = "^7.1.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.flake8]
ignore = "E501,W503"

[tool.black]
line-length = 125
target-version = ["py38"]

[tool.coverage.report]
omit = ["tests/*"]

[tool.poetry.scripts]
catalog = "datalake_catalog.main:cli"

[tool.pytest.ini_options]
addopts = "-ra -v --no-header"
markers = [
  "backends: marks tests requiring a backend database engines",
]
minversion = "6.0"
testpaths = ["tests"]
