version : 1
disable_existing_loggers : False
formatters:
  simple:
    format : '%(asctime)s' - %(name)s - %(pathname)s - %(levelname)s - %(message)s'
handlers:
  file_handler:
    class : logging.handlers.TimedRotatingFileHandler
    level : INFO
    formatter : simple
    filename : 'Tovala_assessment.log'
    when : 'd'
    interval : 1
    'backupCount' : 7
  console_handler:
    class : logging.StreamHandler
    level : INFO
    formatter : simple
    stream : ext://sys.stdout
loggers:
  '':
    level : INFO
    handlers : [file_handler, console_handler]