
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T16:29:54+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "093a60a4607732f406989ec3634d447448f1000e",
 "version": "0.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
