
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-18T23:57:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "664ee0b5f38a65d4ecb919729e9cc90d6d634d29",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
