# -*- coding: utf-8 -*-

"""
youtubesearch

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SearchEnum(object):

    """Implementation of the 'Search' enum.

    Search YouTube for keyword specific results

    Attributes:
        LISTLIST: Returns a collection of search results that match the query
            parameters specified in the API request

    """

    LISTLIST = 'list'
