
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-21T17:15:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb2e47d327e5e969164d5df3201781defed34037",
 "version": "1.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
