
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-18T16:50:27+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ac803480c45953ab1115fafdf79012a5173ba3c",
 "version": "2.5.28.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
