# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from .ledger_pb2 import (
    LedgerSpecifier as org___xrpl___rpc___v1___ledger_pb2___LedgerSpecifier,
    RawLedgerObjects as org___xrpl___rpc___v1___ledger_pb2___RawLedgerObjects,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class GetLedgerDiffRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    include_blobs: builtin___bool = ...
    client_ip: typing___Text = ...

    @property
    def base_ledger(self) -> org___xrpl___rpc___v1___ledger_pb2___LedgerSpecifier: ...

    @property
    def desired_ledger(self) -> org___xrpl___rpc___v1___ledger_pb2___LedgerSpecifier: ...

    def __init__(self,
        *,
        base_ledger : typing___Optional[org___xrpl___rpc___v1___ledger_pb2___LedgerSpecifier] = None,
        desired_ledger : typing___Optional[org___xrpl___rpc___v1___ledger_pb2___LedgerSpecifier] = None,
        include_blobs : typing___Optional[builtin___bool] = None,
        client_ip : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> GetLedgerDiffRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetLedgerDiffRequest: ...
    def HasField(self, field_name: typing_extensions___Literal[u"base_ledger",b"base_ledger",u"desired_ledger",b"desired_ledger"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"base_ledger",b"base_ledger",u"client_ip",b"client_ip",u"desired_ledger",b"desired_ledger",u"include_blobs",b"include_blobs"]) -> None: ...
type___GetLedgerDiffRequest = GetLedgerDiffRequest

class GetLedgerDiffResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def ledger_objects(self) -> org___xrpl___rpc___v1___ledger_pb2___RawLedgerObjects: ...

    def __init__(self,
        *,
        ledger_objects : typing___Optional[org___xrpl___rpc___v1___ledger_pb2___RawLedgerObjects] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> GetLedgerDiffResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetLedgerDiffResponse: ...
    def HasField(self, field_name: typing_extensions___Literal[u"ledger_objects",b"ledger_objects"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"ledger_objects",b"ledger_objects"]) -> None: ...
type___GetLedgerDiffResponse = GetLedgerDiffResponse
