[tool.poetry]
name = "linkhub_prometheus_exporter"
# Version is dynamically managed by `poetry-dynamic-versioning` plugin.
version = "0.4.0"
description = "A Prometheus metrics exporter for Alcatel Linkhub 4G router boxes"
authors = ["Gergely Imreh <gergely@imreh.net>"]
homepage = "https://github.com/imrehg/linkhub_prometheus_exporter"
repository = "https://github.com/imrehg/linkhub_prometheus_exporter"
readme = "README.md"
license = "Apache-2.0"
include = [
    "LICENSE.txt",
]
classifiers = [
    'Development Status :: 3 - Alpha',
    'Framework :: Pytest',
    'Intended Audience :: Information Technology',
    'Intended Audience :: System Administrators',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Topic :: System :: Monitoring',
    'Topic :: System :: Networking :: Monitoring',
    'Typing :: Typed',
]

[tool.poetry.dependencies]
python = "^3.10"
prometheus-client = "^0.14.1"
requests = "^2.27.1"
dynaconf = "^3.1.8"
types-requests = "^2.27.25"
jsonrpcclient = "^4.0.2"

[tool.poetry.group.dev.dependencies]
isort = "*"
black = "*"
nox = "*"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"
requests-mock = "*"
isort = "*"
black = "*"
flake8 = "*"
mypy = "*"
bandit = "*"

[tool.poetry.scripts]
linkhub_exporter = "linkhub_prometheus_exporter.exporter:main"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/imrehg/linkhub_prometheus_exporter/issues"

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]

[tool.black]
line-length = 79

[[tool.mypy.overrides]]
module = [
    "dynaconf",  # Should be necessary while this is open: https://github.com/rochacbruno/dynaconf/issues/448
]
ignore_missing_imports = true

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[build-system]
requires = ["poetry>=1.2.0b1", "poetry-dynamic-versioning-plugin"]
build-backend = "poetry.masonry.api"
