[tool.poetry]
name = "AlectioCLI"
version = "0.1.3"
description = ""
authors = ["Adwitiya <adwitiya.trivedi@alectio.com>", "Raj <raj.jalem@alectio.com>", "Gunjan <gunjan.paul@alectio.com>"]
readme = "README.md"

[tool.poetry.scripts]
alectio-cli = "alectiocli.main:app"

[tool.poetry.dependencies]
python = "^3.7"
typer = {extras = ["all"], version = "^0.4.0"}
requests = "^2.27.1"
PyYAML = "^6.0"
alectio-sdk = "^0.6.21"
"ruamel.yaml" = "^0.17.21"
rich = "^12.2.0"
inquirer = "^2.9.2"
termcolor = "^1.1.0"
pyfiglet = "^0.8.post1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
