name: Deploy new version
on:
  push:
    branches:
      - main


jobs:
  bump_version:
    uses: NationalLibraryOfNorway/DHLAB/.github/workflows/bump-version.yml@main
  upload_package:
    needs: bump_version
    uses: NationalLibraryOfNorway/DHLAB/.github/workflows/upload-package.yml@main
