# Conda environment for dnadna CPU-only
name: dnadna-cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - cython=0.29.23
# future is an indirect dependency of tensorboard (by way of caffe2) that is
# not correctly listed in the package's dependencies as it should be, so we
# must manually list it
  - future=0.18.2
  - jsonschema=3.2.0
  - matplotlib-base=3.4.2
# msprime version is pinned for now due to some trouble with newer versions'
# dependency on openblas not taken into account; this can be fixed later
  - msprime=0.7.3
  - numpy=1.20.3
  - pandas=1.2.3
  - pillow=8.2.0
  - pytorch=1.7.1
  - cpuonly
  - pyyaml=5.4.1
  - scikit-allel=1.3.5
  - setuptools_scm=6.0.1
  - tensorboard=2.4.1
  - tqdm=4.60.0
# Test dependencies
  - filelock=3.0.12
  - pytest=6.2.4
  - pytest-cov=2.12.0
  - pytest-xdist=2.2.1
# Documentation dependencies
  - make=4.3.0
  - sphinx=4.0.2
# Additional pip dependencies
  - pip:
      - jsonschema-pyref>=0.1.0b1
# - for tests
      - mistletoe
      - pytest-doctestplus
# - for docs
      - mistune<2.0  # see https://github.com/Tribler/tribler/issues/6624 
      - m2r
      - pygments-csv-lexer
      - sphinxcontrib-napoleon
      - sphinxcontrib-spelling
      - sphinx-rtd-theme
