language: python
cache: pip

arch:
  - ppc64le
  - arm64
  - s390x

dist: focal

# Only test oldest and newest supported versions
python:
  - "3.7"
  - "3.10"

jobs:
  fast_finish: true

install:
  - pip install -U pip
  - pip install -U pytest
  - pip install .

script: pytest
