# Generated by Django 3.2.6 on 2022-01-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irma', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IrmaQR',
        ),
    ]
