# Generated by Django 4.0.1 on 2022-04-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irma', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IRMA',
        ),
    ]
