
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-22T02:35:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e710e09df79fcceadd37b8b0ccfcd12074a8e000",
 "version": "0.9.dev2221"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
