# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataStructures.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DataStructures.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x44\x61taStructures.proto\"\x1f\n\x07Vector2\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"8\n\x08TeamInfo\x12\x11\n\tteam_name\x18\x01 \x01(\t\x12\x19\n\x07version\x18\x02 \x01(\x0e\x32\x08.Version\"\"\n\x04\x42\x61ll\x12\x1a\n\x08position\x18\x01 \x01(\x0b\x32\x08.Vector2\"0\n\x05Wheel\x12\x12\n\nleft_speed\x18\x01 \x01(\x02\x12\x13\n\x0bright_speed\x18\x02 \x01(\x02\"L\n\x05Robot\x12\x1a\n\x08position\x18\x01 \x01(\x0b\x32\x08.Vector2\x12\x10\n\x08rotation\x18\x02 \x01(\x02\x12\x15\n\x05wheel\x18\x03 \x01(\x0b\x32\x06.Wheel\"h\n\x05\x46ield\x12\x1b\n\x0bself_robots\x18\x01 \x03(\x0b\x32\x06.Robot\x12\x1f\n\x0fopponent_robots\x18\x02 \x03(\x0b\x32\x06.Robot\x12\x13\n\x04\x62\x61ll\x18\x03 \x01(\x0b\x32\x05.Ball\x12\x0c\n\x04tick\x18\x04 \x01(\x05\"8\n\tPlacement\x12\x16\n\x06robots\x18\x01 \x03(\x0b\x32\x06.Robot\x12\x13\n\x04\x62\x61ll\x18\x02 \x01(\x0b\x32\x05.Ball\",\n\x0b\x43ontrolInfo\x12\x1d\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x0c.ControlType*\x1d\n\x07Version\x12\x08\n\x04V1_0\x10\x00\x12\x08\n\x04V1_1\x10\x01**\n\x04Team\x12\x08\n\x04Self\x10\x00\x12\x0c\n\x08Opponent\x10\x01\x12\n\n\x06Nobody\x10\x02*&\n\x0b\x43ontrolType\x12\x0c\n\x08\x43ontinue\x10\x00\x12\t\n\x05Reset\x10\x01\x62\x06proto3'
)

_VERSION = _descriptor.EnumDescriptor(
  name='Version',
  full_name='Version',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='V1_0', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='V1_1', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=489,
  serialized_end=518,
)
_sym_db.RegisterEnumDescriptor(_VERSION)

Version = enum_type_wrapper.EnumTypeWrapper(_VERSION)
_TEAM = _descriptor.EnumDescriptor(
  name='Team',
  full_name='Team',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Self', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Opponent', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Nobody', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=520,
  serialized_end=562,
)
_sym_db.RegisterEnumDescriptor(_TEAM)

Team = enum_type_wrapper.EnumTypeWrapper(_TEAM)
_CONTROLTYPE = _descriptor.EnumDescriptor(
  name='ControlType',
  full_name='ControlType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Continue', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Reset', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=564,
  serialized_end=602,
)
_sym_db.RegisterEnumDescriptor(_CONTROLTYPE)

ControlType = enum_type_wrapper.EnumTypeWrapper(_CONTROLTYPE)
V1_0 = 0
V1_1 = 1
Self = 0
Opponent = 1
Nobody = 2
Continue = 0
Reset = 1



_VECTOR2 = _descriptor.Descriptor(
  name='Vector2',
  full_name='Vector2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vector2.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vector2.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=55,
)


_TEAMINFO = _descriptor.Descriptor(
  name='TeamInfo',
  full_name='TeamInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='team_name', full_name='TeamInfo.team_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='TeamInfo.version', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=113,
)


_BALL = _descriptor.Descriptor(
  name='Ball',
  full_name='Ball',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='Ball.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=149,
)


_WHEEL = _descriptor.Descriptor(
  name='Wheel',
  full_name='Wheel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='left_speed', full_name='Wheel.left_speed', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_speed', full_name='Wheel.right_speed', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=199,
)


_ROBOT = _descriptor.Descriptor(
  name='Robot',
  full_name='Robot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='Robot.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='Robot.rotation', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wheel', full_name='Robot.wheel', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=277,
)


_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='self_robots', full_name='Field.self_robots', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opponent_robots', full_name='Field.opponent_robots', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ball', full_name='Field.ball', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tick', full_name='Field.tick', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=383,
)


_PLACEMENT = _descriptor.Descriptor(
  name='Placement',
  full_name='Placement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='robots', full_name='Placement.robots', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ball', full_name='Placement.ball', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=441,
)


_CONTROLINFO = _descriptor.Descriptor(
  name='ControlInfo',
  full_name='ControlInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='ControlInfo.command', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=487,
)

_TEAMINFO.fields_by_name['version'].enum_type = _VERSION
_BALL.fields_by_name['position'].message_type = _VECTOR2
_ROBOT.fields_by_name['position'].message_type = _VECTOR2
_ROBOT.fields_by_name['wheel'].message_type = _WHEEL
_FIELD.fields_by_name['self_robots'].message_type = _ROBOT
_FIELD.fields_by_name['opponent_robots'].message_type = _ROBOT
_FIELD.fields_by_name['ball'].message_type = _BALL
_PLACEMENT.fields_by_name['robots'].message_type = _ROBOT
_PLACEMENT.fields_by_name['ball'].message_type = _BALL
_CONTROLINFO.fields_by_name['command'].enum_type = _CONTROLTYPE
DESCRIPTOR.message_types_by_name['Vector2'] = _VECTOR2
DESCRIPTOR.message_types_by_name['TeamInfo'] = _TEAMINFO
DESCRIPTOR.message_types_by_name['Ball'] = _BALL
DESCRIPTOR.message_types_by_name['Wheel'] = _WHEEL
DESCRIPTOR.message_types_by_name['Robot'] = _ROBOT
DESCRIPTOR.message_types_by_name['Field'] = _FIELD
DESCRIPTOR.message_types_by_name['Placement'] = _PLACEMENT
DESCRIPTOR.message_types_by_name['ControlInfo'] = _CONTROLINFO
DESCRIPTOR.enum_types_by_name['Version'] = _VERSION
DESCRIPTOR.enum_types_by_name['Team'] = _TEAM
DESCRIPTOR.enum_types_by_name['ControlType'] = _CONTROLTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector2 = _reflection.GeneratedProtocolMessageType('Vector2', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR2,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:Vector2)
  })
_sym_db.RegisterMessage(Vector2)

TeamInfo = _reflection.GeneratedProtocolMessageType('TeamInfo', (_message.Message,), {
  'DESCRIPTOR' : _TEAMINFO,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:TeamInfo)
  })
_sym_db.RegisterMessage(TeamInfo)

Ball = _reflection.GeneratedProtocolMessageType('Ball', (_message.Message,), {
  'DESCRIPTOR' : _BALL,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:Ball)
  })
_sym_db.RegisterMessage(Ball)

Wheel = _reflection.GeneratedProtocolMessageType('Wheel', (_message.Message,), {
  'DESCRIPTOR' : _WHEEL,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:Wheel)
  })
_sym_db.RegisterMessage(Wheel)

Robot = _reflection.GeneratedProtocolMessageType('Robot', (_message.Message,), {
  'DESCRIPTOR' : _ROBOT,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:Robot)
  })
_sym_db.RegisterMessage(Robot)

Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), {
  'DESCRIPTOR' : _FIELD,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:Field)
  })
_sym_db.RegisterMessage(Field)

Placement = _reflection.GeneratedProtocolMessageType('Placement', (_message.Message,), {
  'DESCRIPTOR' : _PLACEMENT,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:Placement)
  })
_sym_db.RegisterMessage(Placement)

ControlInfo = _reflection.GeneratedProtocolMessageType('ControlInfo', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLINFO,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:ControlInfo)
  })
_sym_db.RegisterMessage(ControlInfo)


# @@protoc_insertion_point(module_scope)
