[tool.poetry]
name = "sysource"
version = "1.0"
description = "System widget"
authors = ["Flame <matixsun1@gmail.com>"]
license = "GPL-v3"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
