
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T03:27:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c3ab7a5597016caff121c807571e4e61fb0697f3",
 "version": "1.16.0.post.dev508"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
