jobs:
- job:
  displayName: ubuntu-20.04-conda
  pool:
    vmImage: 'ubuntu-20.04'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name bw2
    displayName: Create Anaconda environment

  - bash: |
      source activate bw2
      conda install --yes --quiet -c defaults -c conda-forge -c cmutel -c haasad --name bw2 python=$PYTHON_VERSION numpy bw_processing matrix_utils pandas scipy psutil pypardiso pytest peewee brightway2 pytest pytest-azurepipelines">=1.0.2" pytest-cov
    displayName: Install Anaconda packages

  - bash: |
      source activate bw2
      pytest --cov=bw2calc --cov-report=xml --cov-report=html
    displayName: pytest

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

- job:
  displayName: ubuntu-20.04-pip
  pool:
    vmImage: 'ubuntu-20.04'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'

  steps:
  - bash: |
      python --version
      pip --version
      pip install --pre numpy bw_processing matrix_utils pandas scipy psutil pypardiso pytest peewee brightway2 pytest pytest-azurepipelines">=1.0.2" pytest-cov
      echo "which pytest"
      which pytest
      echo "pytest version"
      pytest --version
    displayName: Install Pip packages

  - bash: |
      pytest --cov=bw2calc --color=yes -v --cov-report html
    displayName: pytest

- job:
  displayName: macOS-1015-38-conda
  pool:
    vmImage: 'macOS-1015'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'


  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name bw2
    displayName: Create Anaconda environment

  - bash: |
      source activate bw2
      conda install --yes --quiet -c defaults -c conda-forge -c cmutel -c haasad --name bw2 python=$PYTHON_VERSION numpy bw_processing matrix_utils pandas scipy psutil pypardiso pytest peewee brightway2 pytest pytest-azurepipelines">=1.0.2" pytest-cov
    displayName: Install Anaconda packages

  - bash: |
      source activate bw2
      pytest --cov=bw2calc --cov-report=xml --cov-report=html
    displayName: pytest

- job:
  displayName: windows-2019-conda
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name bw2
    displayName: Create Anaconda environment

  - script: |
      call activate bw2
      conda install --yes --quiet -c defaults -c conda-forge -c cmutel -c haasad --name bw2 python=%PYTHON_VERSION% numpy bw_processing matrix_utils pandas scipy psutil pypardiso pytest peewee brightway2 pytest pytest-azurepipelines">=1.0.2" pytest-cov
    displayName: Install Anaconda packages

  - script: |
      call activate bw2
      pytest --cov=bw2calc --cov-report=xml --cov-report=html
    displayName: pytest
