
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-17T17:12:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8406d1661ba6efe7fd67670717bf25daeb608e6e",
 "version": "2022.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
