
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-23T12:16:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d34e9a7839436b0922cda9864ea632c33add47e",
 "version": "1.1.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
