
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T16:45:56+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a81db3c7a2898f87377a7efc46b32870900a8f5a",
 "version": "0.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
