
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T06:26:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "73ff28f468af6b7550df26935df33df1c6c5e855",
 "version": "1.16.0.post.dev528"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
