
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-16T23:28:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f48e1e1cdad0372edcff200eccdafd5be9eec315",
 "version": "0.0.93"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
