[build-system]
requires = ["setuptools>=61", "wheel", "numpy>=1.22.3","tensorflow==2.6.0","astropy==5.0.4","scipy==1.7.3", "matplotlib == 3.5.1", "photutils == 1.4.0", "pandas==1.4.1"]
build-backend = "setuptools.build_meta"