
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-23T03:52:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "00e240b4386d09af57292a826d6bbef575000166",
 "version": "1.16.0.post.dev541"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
