[tool.poetry]
name = "fa_purity"
version = "1.18.1"
description = "Pure functional and typing utilities"
authors = ["Product Team <development@fluidattacks.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Deprecated = "^1.2.12"
more-itertools = "^8.10.0"
simplejson = "^3.17.6"
types-simplejson = "^3.17.2"
types-Deprecated = "^1.2.1"
typing-extensions = "^4.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
