
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-21T10:52:21-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "edcd0da5d92fa582956a67ebe00d89e85882d193",
 "version": "2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
