
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T05:37:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a67f84db10258e53d296abd2cd8ad4431eca2ece",
 "version": "1.16.0.post.dev522"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
