name: ebuildtester
base: core20
adopt-info: ebuildtester
summary: Tool to test a Gentoo ebuild and its dependencies
description: |
    This script is a tool to test a Gentoo ebuild and its dependencies. The
    idea is that the package is emerged in a clean (and current) stage3 Docker
    container.
grade: stable
confinement: strict

environment:
  DOCKER_COMMAND: docker-wrapper.sh

plugs:
  docker-executables:
    interface: content
    target: $SNAP/docker-snap
    default-provider: docker

apps:
  ebuildtester:
    command: bin/ebuildtester
  docker:
    command: usr/bin/docker-wrapper.sh
    plugs:
      - docker

parts:
  ebuildtester:
    plugin: python
    source: https://github.com/nicolasbock/ebuildtester.git
    source-type: git
    source-tag: v0.1.35
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe)"
    requirements:
      - requirements.txt
  docker-wrapper:
    plugin: dump
    source: .
    organize:
      docker-wrapper.sh: /usr/bin/docker-wrapper.sh
