
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T19:25:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ade926b1827f32653a9697d5eb832105156b891d",
 "version": "0.2.0.post0.dev89"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
