
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-16T19:11:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "90ca567230dce39681ed5b826b438dd8391dbd8e",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
