
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-17T10:00:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "eafb56df702bc62080653f33225cad34cd9d1942",
 "version": "2.0.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
