name: Publish to TestPyPI

on:
  # Publish to TestPyPI when we push to master
  push:
    branches: [ master ]

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools build wheel twine
    - name: Build
      run: |
        python -m build --sdist --outdir dist/
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_SECRET }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true
        print_hash: true
