
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-23T14:02:10+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "53e8982e47fedca1c34fccffacf89e515c859c3d",
 "version": "0.0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
