# Generated by Django 2.2.3 on 2022-05-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220505_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='counter',
        ),
    ]
