# Generated by Django 2.2.3 on 2022-05-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
