# Generated by Django 3.2.13 on 2022-05-18 01:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220506_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(default='files.jpg', upload_to=users.models.UserProfile.content_file_name),
            preserve_default=False,
        ),
    ]
