# Generated by Django 3.2.13 on 2022-05-18 01:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220518_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qrcode',
            field=models.FileField(blank=True, null=True),
        ),
    ]
