# Generated by Django 3.2.13 on 2022-05-18 01:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=users.models.UserProfile.content_file_name),
        ),
    ]
