# Generated by Django 3.2.13 on 2022-05-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qrcode',
        ),
    ]
