# Generated by Django 3.2.13 on 2022-05-18 02:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='qrcode',
            field=models.FileField(blank=True, null=True),
        ),
    ]
