# Generated by Django 3.2.13 on 2022-05-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userprofile_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='qrcode',
        ),
    ]
