[tool.black]
line-length = 100
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = 'typings/'

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--verbose --cov --cov-report xml --cov-report term --cov-report html"
testpaths = ["tests"]
filterwarnings = ["ignore::DeprecationWarning:rdkit.*:"]

[tool.coverage.run]
omit = ["setup.py", "tests/*", "SA_Score/*"]

[tool.coverage.xml]
output = "coverage.xml"

[tool.mypy]
exclude = []
ignore_missing_imports = true
