
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T10:30:44-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e35c2d570b6a4f5db7a8c12950b57692ab23b0bb",
 "version": "1.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
