# Conda environment for dnadna GPU
name: dnadna
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - coloredlogs>=15.0.0
  - cython>=0.29.17,<3.0.0
  - cudatoolkit>=10.0.130-0
# future is an indirect dependency of tensorboard (by way of caffe2) that is
# not correctly listed in the package's dependencies as it should be, so we
# must manually list it
  - future>=0.18.2
  - jsonschema>=3.0.2
  - matplotlib-base>=3.1.1
# msprime version is pinned for now due to some trouble with newer versions'
# dependency on openblas not taken into account; this can be fixed later
# Additional pip dependencies
  - msprime=0.7.3
  - numpy>=1.19.5
  - pandas>=0.25.1,<1.4.0
  - pillow>=6.2.1
  - pytorch>=1.2.0
  - pyyaml>=5.1.2
  - scikit-allel>=1.2.1
  - setuptools_scm>=4.1.2
  - tensorboard>=2.2.1
  - tqdm>=4.40.0
# Test dependencies
  - filelock>=3.0.12
  - pytest>=5.3.1
  - pytest-cov>=2.8.1
  - pytest-xdist>=1.31.0
# Documentation dependencies
  - make>=4.2.1
  - sphinx>=2.4.0
# Pin to suppress deprecation warnings:
# https://github.com/python/importlib_metadata/issues/298
  - importlib_metadata<3.9
# Additional pip dependencies
  - pip:
      - jsonschema-pyref
# - for tests
      - mistletoe
      - pytest-doctestplus
# - for docs
      - mistune<2.0  # see https://github.com/Tribler/tribler/issues/6624 
      - m2r
      - pygments-csv-lexer
      - sphinxcontrib-napoleon
      - sphinxcontrib-spelling
      - sphinx-rtd-theme
