
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-17T17:15:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a040ad372b5e6adb8687a89259434e402ea1b43",
 "version": "2.4.3rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
