{% set name = load_setup_py_data().get('name') %}
{% set version = load_setup_py_data().get('version') %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - jsonschema >=3.0.0
    - jsonschema-pyref >=0.1.0
    - matplotlib-base >=3.1.0
    - msprime >=0.7.0
    - numpy >=1.19.0
    - pandas >=0.25.0
    - python >=3.7
    - pyyaml >=5.1.0
    - scikit-allel >=1.2.0
    - pytorch >=1.2.0
    - tqdm >=4.40.0
    # Needed for msprime but not listed in its dependencies
    - openblas
    - python-newick >=1.3.0

test:
  imports:
    - dnadna
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/mlgenetics/dnadna
  summary: Deep Neural Architecture for DNA
  license_file: LICENSE.md
