import datetime
menu_data = [
    {
        "id": 21,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "icon": "upload",
        "name": "升级中心",
        "sort": 4,
        "is_link": 0,
        "is_catalog": 1,
        "web_path": "",
        "component": "",
        "component_name": "",
        "status": 1,
        "cache": 0,
        "visible": 1,
        "creator_id": 1,
        "parent_id": None
    },
    {
        "id": 22,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "icon": "cart-plus",
        "name": "应用管理",
        "sort": 1,
        "is_link": 0,
        "is_catalog": 0,
        "web_path": "/application",
        "component": "plugins/dvadmin-upgrade-center-web/src/application/index",
        "component_name": "application",
        "status": 1,
        "cache": 0,
        "visible": 1,
        "creator_id": 1,
        "parent_id": 21
    },
    {
        "id": 23,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "icon": "television",
        "name": "应用版本",
        "sort": 2,
        "is_link": 0,
        "is_catalog": 0,
        "web_path": "/appVersion",
        "component": "plugins/dvadmin-upgrade-center-web/src/appVersion/index",
        "component_name": "appVersion",
        "status": 1,
        "cache": 0,
        "visible": 0,
        "creator_id": 1,
        "parent_id": 21
    },
    {
        "id": 24,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "icon": "clock-o",
        "name": "升级日志",
        "sort": 4,
        "is_link": 0,
        "is_catalog": 0,
        "web_path": "/upgradeLogging",
        "component": "plugins/dvadmin-upgrade-center-web/src/upgradeLogging/index",
        "component_name": "upgradeLogging",
        "status": 1,
        "cache": 0,
        "visible": 1,
        "creator_id": 1,
        "parent_id": 21
    },
    {
        "id": 25,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "icon": "desktop",
        "name": "设备管理",
        "sort": 3,
        "is_link": 0,
        "is_catalog": 0,
        "web_path": "/appDeviceManage",
        "component": "plugins/dvadmin-upgrade-center-web/src/appDeviceManage/index",
        "component_name": "appDeviceManage",
        "status": 1,
        "cache": 0,
        "visible": 1,
        "creator_id": 1,
        "parent_id": 21
    }
]


menu_button_data = [
    {
        "id": 57,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/dvadmin_upgrade_center/app_version/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 22
    },
    {
        "id": 58,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/dvadmin_upgrade_center/app_version/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 22
    },
    {
        "id": 59,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "api": "/api/dvadmin_upgrade_center/app_version/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 22
    },
    {
        "id": 60,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "新增",
        "value": "Create",
        "api": "/api/dvadmin_upgrade_center/app_version/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 22
    },
    {
        "id": 61,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "api": "/api/dvadmin_upgrade_center/app_version/{id}/",
        "method": 3,
        "creator_id": 1,
        "menu_id": 22
    },
    {
        "id": 62,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/dvadmin_upgrade_center/app_version/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 23
    },
    {
        "id": 63,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/dvadmin_upgrade_center/app_version/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 23
    },
    {
        "id": 64,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "新增",
        "value": "Create",
        "api": "/api/dvadmin_upgrade_center/app_version/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 23
    },
    {
        "id": 65,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "api": "/api/dvadmin_upgrade_center/app_version/{id}/",
        "method": 3,
        "creator_id": 1,
        "menu_id": 23
    },
    {
        "id": 66,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "api": "/api/dvadmin_upgrade_center/app_version/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 23
    },
    {
        "id": 67,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/dvadmin_upgrade_center/app_device_manage/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 25
    },
    {
        "id": 68,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/dvadmin_upgrade_center/app_device_manage/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 25
    },
    {
        "id": 69,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/dvadmin_upgrade_center/upgrade_logging/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 24
    },
    {
        "id": 70,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/dvadmin_upgrade_center/upgrade_logging/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 24
    }
]

dictionary_data = [
    {
        "id": 22,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "升级中心版本发布平台",
        "value": "upgrade_center_platform",
        "status": 1,
        "sort": 7,
        "remark": None,
        "creator_id": 1,
        "parent_id": None,
        "is_value": 0,
        "type": 0,
        "color": None
    },
    {
        "id": 23,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "Windows",
        "value": "0",
        "status": 1,
        "sort": 0,
        "remark": None,
        "creator_id": 1,
        "parent_id": 22,
        "is_value": 1,
        "type": 1,
        "color": "success"
    },
    {
        "id": 24,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "Linux",
        "value": "1",
        "status": 1,
        "sort": 1,
        "remark": None,
        "creator_id": 1,
        "parent_id": 22,
        "is_value": 1,
        "type": 1,
        "color": None
    },
    {
        "id": 25,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "Android",
        "value": "2",
        "status": 1,
        "sort": 2,
        "remark": None,
        "creator_id": 1,
        "parent_id": 22,
        "is_value": 1,
        "type": 1,
        "color": None
    },
    {
        "id": 26,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "Apple",
        "value": "3",
        "status": 1,
        "sort": 3,
        "remark": None,
        "creator_id": 1,
        "parent_id": 22,
        "is_value": 1,
        "type": 1,
        "color": None
    },
    {
        "id": 27,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "升级中心版本状态",
        "value": "upgrade_center_version_status",
        "status": 1,
        "sort": 8,
        "remark": None,
        "creator_id": 1,
        "parent_id": None,
        "is_value": 0,
        "type": 0,
        "color": None
    },
    {
        "id": 28,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "待上线",
        "value": "0",
        "status": 1,
        "sort": 0,
        "remark": None,
        "creator_id": 1,
        "parent_id": 27,
        "is_value": 1,
        "type": 1,
        "color": None
    },
    {
        "id": 29,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "正式发布",
        "value": "1",
        "status": 1,
        "sort": 1,
        "remark": None,
        "creator_id": 1,
        "parent_id": 27,
        "is_value": 1,
        "type": 1,
        "color": "success"
    },
    {
        "id": 30,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "版本回滚",
        "value": "3",
        "status": 1,
        "sort": 3,
        "remark": None,
        "creator_id": 1,
        "parent_id": 27,
        "is_value": 1,
        "type": 1,
        "color": ""
    },
    {
        "id": 31,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "灰度内测",
        "value": "2",
        "status": 1,
        "sort": 2,
        "remark": None,
        "creator_id": 1,
        "parent_id": 27,
        "is_value": 1,
        "type": 1,
        "color": ""
    },
    {
        "id": 32,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "下线",
        "value": "4",
        "status": 1,
        "sort": 4,
        "remark": None,
        "creator_id": 1,
        "parent_id": 27,
        "is_value": 1,
        "type": 1,
        "color": None
    },
    {
        "id": 33,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "升级中心日志类型",
        "value": "upgrade_center_logging_type",
        "status": 1,
        "sort": 9,
        "remark": None,
        "creator_id": 1,
        "parent_id": None,
        "is_value": 0,
        "type": 0,
        "color": None
    },
    {
        "id": 34,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "正常升级",
        "value": "0",
        "status": 1,
        "sort": 0,
        "remark": None,
        "creator_id": 1,
        "parent_id": 33,
        "is_value": 1,
        "type": 1,
        "color": "primary"
    },
    {
        "id": 35,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "手动升级",
        "value": "1",
        "status": 1,
        "sort": 1,
        "remark": None,
        "creator_id": 1,
        "parent_id": 33,
        "is_value": 1,
        "type": 1,
        "color": None
    },
    {
        "id": 36,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "灰度内测",
        "value": "2",
        "status": 1,
        "sort": 1,
        "remark": None,
        "creator_id": 1,
        "parent_id": 33,
        "is_value": 1,
        "type": 1,
        "color": "info"
    },
    {
        "id": 37,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "版本回滚",
        "value": "3",
        "status": 1,
        "sort": 3,
        "remark": None,
        "creator_id": 1,
        "parent_id": 33,
        "is_value": 1,
        "type": 1,
        "color": None
    },
    {
        "id": 38,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "错误日志",
        "value": "4",
        "status": 1,
        "sort": 4,
        "remark": None,
        "creator_id": 1,
        "parent_id": 33,
        "is_value": 1,
        "type": 1,
        "color": "danger"
    },
    {
        "id": 39,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "无变化",
        "value": "-1",
        "status": 1,
        "sort": -1,
        "remark": None,
        "creator_id": 1,
        "parent_id": 33,
        "is_value": 1,
        "type": 1,
        "color": "success"
    },
    {
        "id": 40,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "升级中心设备升级类型",
        "value": "upgrade_center_upgrade_type",
        "status": 1,
        "sort": 10,
        "remark": None,
        "creator_id": 1,
        "parent_id": None,
        "is_value": 0,
        "type": 0,
        "color": None
    },
    {
        "id": 41,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "手动升级",
        "value": "1",
        "status": 1,
        "sort": 1,
        "remark": None,
        "creator_id": 1,
        "parent_id": 40,
        "is_value": 1,
        "type": 1,
        "color": None
    },
    {
        "id": 42,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "灰度内测",
        "value": "2",
        "status": 1,
        "sort": 2,
        "remark": None,
        "creator_id": 1,
        "parent_id": 40,
        "is_value": 1,
        "type": 1,
        "color": None
    },
    {
        "id": 43,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "版本回滚",
        "value": "3",
        "status": 1,
        "sort": 3,
        "remark": None,
        "creator_id": 1,
        "parent_id": 40,
        "is_value": 1,
        "type": 1,
        "color": None
    },
    {
        "id": 44,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "升级中心设备升级状态",
        "value": "upgrade_center_upgrade_status",
        "status": 1,
        "sort": 11,
        "remark": None,
        "creator_id": 1,
        "parent_id": None,
        "is_value": 0,
        "type": 0,
        "color": None
    },
    {
        "id": 45,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "待完成",
        "value": "0",
        "status": 1,
        "sort": 0,
        "remark": None,
        "creator_id": 1,
        "parent_id": 44,
        "is_value": 1,
        "type": 1,
        "color": "primary"
    },
    {
        "id": 46,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "已完成",
        "value": "1",
        "status": 1,
        "sort": 1,
        "remark": None,
        "creator_id": 1,
        "parent_id": 44,
        "is_value": 1,
        "type": 1,
        "color": "success"
    },
    {
        "id": 47,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "已失效",
        "value": "2",
        "status": 1,
        "sort": 2,
        "remark": None,
        "creator_id": 1,
        "parent_id": 44,
        "is_value": 1,
        "type": 1,
        "color": "info"
    },
    {
        "id": 48,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "label": "手动取消",
        "value": "3",
        "status": 1,
        "sort": 3,
        "remark": None,
        "creator_id": 1,
        "parent_id": 44,
        "is_value": 1,
        "type": 1,
        "color": "info"
    }
]
