## Project requirements (PEP 518, https://python-poetry.org/).


[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]


[tool.black]
line-length = 96
target-version = ["py38", "py39", "py310"]


[tool.isort]
line_length = 96
profile = "black"


[tool.mypy]
explicit_package_bases = true
namespace_packages = true

check_untyped_defs = true
strict_optional = true
no_implicit_optional = true

warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true

color_output = false
pretty = true
show_error_codes = true

incremental = true
cache_dir = ".mypy"
sqlite_cache = true


[tool.poetry]
name = "osg_jupyter"
version = "1.0.0"
description = "Support for OSG for Project Jupyter"
license = "Apache-2.0"
authors = ["Brian Aydemir <baydemir@morgridge.org>"]
repository = "https://github.com/brianaydemir/osg-jupyter"
packages = [{ include = "osg" }]


[tool.poetry.dependencies]
## These dependencies are intended for jupyterhub/k8s-hub:0.11.1.
python = "~3.8"
cryptography = "~3.3,>=3.3.2"  # 3.2 -> 3.3 for security weaknesses
kubernetes = "~12.0"
ldap3 = "~2.8"
PyJWT = "~1.7"
PyYAML = "~5.4"  # 5.3 -> 5.4 for types-PyYAML


[tool.poetry.dev-dependencies]
bandit = "~1.7"
black = "~22.3"
docutils = "~0.18"
isort = "~5.10"
mypy = "~0.950"
pre-commit = "~2.19"
pylint = "~2.13"
"ruamel.yaml.cmd" = "~0.5"
safety = "~1.10"
types-PyYAML = "~5.4"


[tool.pylint.messages-control]
max-line-length = 96
disable = "invalid-name,missing-class-docstring,missing-function-docstring"
