[tool.poetry]
name = "pythogen"
version = "0.0.1"
description = ""
authors = []

[tool.poetry.dependencies]
python = "3.9.*"
typer = "0.4.1"
pyyaml = "6.0"
jinja2 = "3.1.1"
rich = "12.2.0"
inflection = "0.5.1"


[build-system]
requires = ["poetry>=1.1.0"]
build-backend = "poetry.masonry.api"
