__version__ = '0.0.2'
__title__ = 'zwdocs'
__description__ = 'Personal Document Utilities'
__url__ = 'https://github.com/njzhaowei/zwdocs'
__author__ = 'Zhao Wei'
__author_email__ = 'yewberry@163.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2022 Zhao Wei. All rights reserved.'
