
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T04:11:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0693d672ea069f86cb53021abdbe9fcd44152f5",
 "version": "1.16.0.post.dev536"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
