version: "3"

services:
  offer_service:
    build: .
    networks:
      - main_network
    ports:
      - 8002:8002

  offer_service_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgres/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - main_network
    ports:
      - 5435:5432

networks:
  main_network:
    driver: bridge

volumes:
  postgres:
