
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-21T12:53:32-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "95f4486c25ead4f1e6bce54d9704706491334d2a",
 "version": "2.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
