[tool.poetry]
authors = ["Tom Whitwell <tom@whi.tw>"]
description = "Parser + generator for Changelogs of spec from https://keepachangelog.com/en/1.0.0/"
name = "python-keepachangelog"
version = "0.0.1"

[tool.poetry.dependencies]
python = "^3.10"
semver = "^2.13.0"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
black = "^22.3.0"
flake8 = "^4.0.1"
isort = "^5.10.1"
pytest = "^7.1"
pytest-cov = "^3.0.0"
pytest-watch = "^4.2.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
