
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-22T22:14:03+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "5f9e26f4125d8aa7776377f561d22ca1a6bc92c2",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
