
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-07T11:14:12+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea7130e4c655b320d9a858b7f3604a271bb26b0d",
 "version": "1.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
