
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-21T12:43:56-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "617450c47b036b4f6c7496b76699591b15390102",
 "version": "3.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
