
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-18T18:01:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a45f9ae756ee1828c0a326365e13ef6a232fae8e",
 "version": "0.2.0.post0.dev71"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
