
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T13:33:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "31be6edc01ff89f56ca8391fb1410d210a73b441",
 "version": "0.2.0.post0.dev77"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
