
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T03:17:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5bc4e5ddc939ab65314486197e604f04b7bed762",
 "version": "0.1.1a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
