[tool.poetry]
name = "sber_ld_dbtools"
version = "0.0.7"
description = "Tools for interacting with LD databases."
authors = ["Andrew Sonin <sonin.cel@yandex.ru>"]
repository = "https://github.com/andrewsonin/sber_ld_dbtools"
homepage = "https://github.com/andrewsonin/sber_ld_dbtools"
readme = "README.md"
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1"
pandakeeper = "^0.0.25"
varutils = "^0.0.6"
psycopg2-binary = "^2"
teradatasql = "^17"
pyspark = "^2"
JPype1 = "^1"
JayDeBeApi = "^1"

[tool.poetry.dev-dependencies]
numpy = "~1.20"
pandas = "~1.1"
ipython = "^7"
mypy = ">=0.950"
toml = "^0.10"
types-toml = "^0.10"
types-setuptools = "^57"
pandas-stubs = "^1"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=62", "toml>=0.10,<0.11"]
build-backend = "poetry.core.masonry.api"
