# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from .ledger_pb2 import (
    LedgerSpecifier as org___xrpl___rpc___v1___ledger_pb2___LedgerSpecifier,
    RawLedgerObjects as org___xrpl___rpc___v1___ledger_pb2___RawLedgerObjects,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class GetLedgerDataRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    marker: builtin___bytes = ...
    end_marker: builtin___bytes = ...
    client_ip: typing___Text = ...
    user: typing___Text = ...

    @property
    def ledger(self) -> org___xrpl___rpc___v1___ledger_pb2___LedgerSpecifier: ...

    def __init__(self,
        *,
        marker : typing___Optional[builtin___bytes] = None,
        ledger : typing___Optional[org___xrpl___rpc___v1___ledger_pb2___LedgerSpecifier] = None,
        end_marker : typing___Optional[builtin___bytes] = None,
        client_ip : typing___Optional[typing___Text] = None,
        user : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> GetLedgerDataRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetLedgerDataRequest: ...
    def HasField(self, field_name: typing_extensions___Literal[u"ledger",b"ledger"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"client_ip",b"client_ip",u"end_marker",b"end_marker",u"ledger",b"ledger",u"marker",b"marker",u"user",b"user"]) -> None: ...
type___GetLedgerDataRequest = GetLedgerDataRequest

class GetLedgerDataResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    ledger_index: builtin___int = ...
    ledger_hash: builtin___bytes = ...
    marker: builtin___bytes = ...
    is_unlimited: builtin___bool = ...

    @property
    def ledger_objects(self) -> org___xrpl___rpc___v1___ledger_pb2___RawLedgerObjects: ...

    def __init__(self,
        *,
        ledger_index : typing___Optional[builtin___int] = None,
        ledger_hash : typing___Optional[builtin___bytes] = None,
        ledger_objects : typing___Optional[org___xrpl___rpc___v1___ledger_pb2___RawLedgerObjects] = None,
        marker : typing___Optional[builtin___bytes] = None,
        is_unlimited : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> GetLedgerDataResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetLedgerDataResponse: ...
    def HasField(self, field_name: typing_extensions___Literal[u"ledger_objects",b"ledger_objects"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"is_unlimited",b"is_unlimited",u"ledger_hash",b"ledger_hash",u"ledger_index",b"ledger_index",u"ledger_objects",b"ledger_objects",u"marker",b"marker"]) -> None: ...
type___GetLedgerDataResponse = GetLedgerDataResponse
