[build-system]
requires = [ "setuptools >= 35.0.2", "wheel >= 0.29.0", "twine", "cython >= 0.29.28,<3.0" ]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py36', 'py37', 'py38']


[tool.pytest.ini_options]
testpaths = ["tests"]
