
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-23T15:01:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3646441c5438118c455f54d336547b1822c3076c",
 "version": "1.1.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
