[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
[tool.semantic_release]
version_variable = [
    'Trinnuty/__init__.py:__version__',
]
dynamic = ["version"]