GROUP_KEY_CLIENT_ATTRIBUTE_NAME = 'groupKey'
MESSAGE_KEY_CLIENT_ATTRIBUTE_NAME = 'messageKey'

MESSAGE_KEY_KEY = 'key'
MESSAGE_QUEUE_KEY_KEY = 'queueKey'
MESSAGE_GROUP_KEY = 'groupKey'
MESSAGE_CONTENT_KEY = 'content'
