
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T10:37:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "58323d27ef7bdae8d81201b86d8a196d0a9632c8",
 "version": "2022.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
