
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-21T00:10:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ce5ca7acf8c1bb5a06361d50d23b651576576bb",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
