
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-18T12:24:36+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "45d572fa86ad0d94db8bf13ff779cb8c05d8d459",
 "version": "1.0.8rc12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
