[tool.poetry]
name = "readtime_cli"
version = "0.1.0"
description = ""
authors = ["Felipe Guedes <contatofelipeguedes@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
readtime = "readtime_cli.main:app"

[tool.poetry.dependencies]
python = "^3.9"
readtime = "^1.1.1"
typer = "^0.4.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
blue = "^0.9.0"
isort = "^5.10.1"
pip-audit = "^2.2.1"
prospector = { extras = ["with_mypy"], version = "^1.7.7" }
pytest-cov = "^3.0.0"
ipdb = "^0.13.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
