
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-17T13:17:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c33bb9570a4c65e587462b40536bedb78b8eddd",
 "version": "1.28.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
