# coding: utf-8

"""
    Seeq REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 54.3.2-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DirectiveUpdatedInputV1(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'directive_name': 'str',
        'version': 'str'
    }

    attribute_map = {
        'directive_name': 'directiveName',
        'version': 'version'
    }

    def __init__(self, directive_name=None, version=None):
        """
        DirectiveUpdatedInputV1 - a model defined in Swagger
        """

        self._directive_name = None
        self._version = None

        if directive_name is not None:
          self.directive_name = directive_name
        if version is not None:
          self.version = version

    @property
    def directive_name(self):
        """
        Gets the directive_name of this DirectiveUpdatedInputV1.
        Directive Name

        :return: The directive_name of this DirectiveUpdatedInputV1.
        :rtype: str
        """
        return self._directive_name

    @directive_name.setter
    def directive_name(self, directive_name):
        """
        Sets the directive_name of this DirectiveUpdatedInputV1.
        Directive Name

        :param directive_name: The directive_name of this DirectiveUpdatedInputV1.
        :type: str
        """
        if directive_name is None:
            raise ValueError("Invalid value for `directive_name`, must not be `None`")

        self._directive_name = directive_name

    @property
    def version(self):
        """
        Gets the version of this DirectiveUpdatedInputV1.
        Version name

        :return: The version of this DirectiveUpdatedInputV1.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this DirectiveUpdatedInputV1.
        Version name

        :param version: The version of this DirectiveUpdatedInputV1.
        :type: str
        """

        self._version = version

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DirectiveUpdatedInputV1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
