
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-21T13:12:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4895e04b00509b594ce1ed8952d3d5cd55fa5566",
 "version": "v0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
