
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T21:59:36-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a58ec75a2fb04954b18098fb0d1d8c9169d1d9f",
 "version": "0.1.1a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
