
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-18T15:20:50+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b2379d446392c0f205fd965505c341a7bd1ba52",
 "version": "1.0.8rc13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
