
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-18T10:18:27-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e2bb47cbd6f3d4b84b08412ffe5025d0d218de09",
 "version": "0.0.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
