
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T04:21:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4fa23eab81945b62517aefda170cf00fa261ea8f",
 "version": "1.16.0.post.dev513"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
