
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-16T17:26:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c8a69066a0841847752116e35e84754e4e01422b",
 "version": "0.1.82"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
