# Generated by Django 4.0.1 on 2022-03-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('irma', '0002_delete_irmaqr'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('irma_verified', 'irma verified'),),
            },
        ),
    ]
