# SPDX-FileCopyrightText: 2022 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Test Release
on: workflow_dispatch

jobs:

  test-release:
  
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py: ['3.6', '3.10']
    
    runs-on: ${{ matrix.os }}
    
    steps:
    
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py }}
      
      - name: Install/update packages
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -U setuptools wheel
          python3 -m pip install -U pypdfium2 pillow pytest
      
      - name: Check out pypdfium2 repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      
      - name: Run tests
        run: make test
  
  test-release-arm:
    
    strategy:
      fail-fast: false
      matrix:
        os: [fedora_latest]
        cpu: [armv7, aarch64]
    
    runs-on: ubuntu-latest
    name: ${{ matrix.os }} ${{ matrix.cpu }} (emulated)
    
    steps:
    
      - uses: uraimo/run-on-arch-action@v2
        name: Perform emulated installation
        id: install
        with:
          arch: ${{ matrix.cpu }}
          distro: ${{ matrix.os }}
          githubToken: ${{ github.token }}
          install: |
            dnf -y update
            dnf -y install git python3-pip python3-wheel python3-pytest python3-pillow
          run: |
            python3 -m pip install pypdfium2
            git clone --depth 1 "https://github.com/pypdfium2-team/pypdfium2.git"
            cd pypdfium2
            python3 -m pytest ./tests/
