[tool.isort]
profile = "black"
combine_as_imports = true
skip = ["tests/imports.pyi"]

[tool.black]
force-exclude = ".*\\.pyi"

[tool.mypy]
show_error_codes = true
strict = true
enable_error_code = "ignore-without-code"
warn_unreachable = true
allow_subclassing_any = true
allow_untyped_defs = true
allow_incomplete_defs = true

[tool.pytest.ini_options]
addopts = "--doctest-modules"
