
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-17T11:20:17-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cd152fb64882a45b4f408c181dfab33157e0351",
 "version": "4.14.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
