
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-23T14:05:51+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "09dfd347dd7c47b5d05a04c9b70291cc9d1971c5",
 "version": "0.28.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
