
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-22T17:08:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc91e9a5d1630272a788942ba62d64ab8ede2076",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
