
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-16T16:37:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bbed20f7c1de220353715838716e0de80e694b8e",
 "version": "7.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
