[tool.poetry]
name = "ceader"
version = "0.0.9"
description = "Header adding service"
authors = [
    "Kamil Jankowski <kamil@cerebre.io>",
]


[tool.poetry.dependencies]
python = ">=3.9,<3.10"




[tool.poetry.dev-dependencies]
black = "^22.3.0"
mypy = "^0.910"
autoflake = "^1.4"
isort = "^5.9.2"
bandit = "^1.7.4"
click = "^8.1.2"
pytest = "^7.1.1"
coverage-badge = "^1.1.0"
pre-commit = "^2.17.0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79

[tool.black]
line-length = 79
target-version = ['py39']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/

)
'''