
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-22T22:15:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b875ed0b9540795ca0593b147b1a49445f3c9274",
 "version": "1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
