
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T11:08:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "98902e44e771d7d9216b34d86b14ee6ce2acc9a5",
 "version": "1.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
