
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-17T08:42:32-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "38335334db33f19ab8de530332f5b4e7c9736142",
 "version": "v2.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
