
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T11:13:40+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1e250b4a640fbdf4f7954ca22b4c4db038c73c5f",
 "version": "0.15.6a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
