
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-23T15:06:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4bc062932655a75be60a70b12938dadeca34acab",
 "version": "2674"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
