[tool.poetry]
name = "cecily"
version = "0.1.1"
description = "Minimalistic task queue using just the stdlib"
authors = ["Nick Yu <nickyu42@gmail.com>"]
license = "MIT"
packages = [
    { include = "cecily" },
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119