
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T14:06:07+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a736051a23adf6041a098c3563399196ca233895",
 "version": "2.9.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
