
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-20T01:36:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a08c5a3d29118205beebfcea60fc0cfae51757db",
 "version": "0.19.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
