
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-17T17:11:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "be1bffe20cc585c6eb6408a30afb2e6cbfde8730",
 "version": "3.1.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
