[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "triangle_drawer"
authors = [{name = "Deividas Tamkus", email = "dtamkus@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = ["matplotlib >= 3.5.2, < 4"]

[project.urls]
Home = "https://github.com/deitam/TriangleDrawer"
