[tool.poetry]
name = "dodgem"
version = "1.0.1"
description = "Version bumper for Python."
readme = "README.md"
repository = "https://github.com/lambdacasserole/dodgem.git"
authors = ["Saul Johnson <saul.a.johnson@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
blessings = "^1.7"
click = "^8.1.3"
tomlkit = "^0.10.2"
semver = "^2.13.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
