
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-18T11:11:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "83bc4b6112d6222492a9dca53a7b7cd8581b4954",
 "version": "2.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
