
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-17T14:03:55-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c2cadc40ce8a8f6d58952c9c9d96411c7d58e15",
 "version": "v2.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
