[tool.poetry]
name = "qiskit-qryd-provider"
version = "0.2.8"
description = "Qiskit provider for accessing the emulator and future Rydberg quantum computer of the QRydDemo consortium"
authors = ["Sebastian Weber"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
qiskit-terra = "^0.20.0"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
qiskit-aer = "^0.10.3"
pydot = "^1.4.2"
Pillow = "^9.1.0"
pytest = "^7.1.1"
networkx = ">=2.6.3"
numpy = ">=1.21.6"
flake8 = "^4.0.1"
flake8-bugbear = "^22.3.23"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
