
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T23:29:12-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ac18dc156a4e4a0ef0b12f441b8e26c429675be",
 "version": "2.6.6.dev20220521"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
