
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-17T14:11:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "41cdeef848e60aeea6bb9841143ad59a61b7a1de",
 "version": "1.16.0.post.dev506"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
