
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T09:41:54+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b205501d76eb6b21ebce31a54f584f8c5d3d4271",
 "version": "2.9.49.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
