[tool.poetry]
name = "pyaes256_encrypter"
version = "1.0.3"
description = "A package to simplify the use of AES-256 encryption with random initialization vector."
authors = ["Maicon Renildo <maicon.renildo1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.3"]
build-backend = "poetry.core.masonry.api"
