
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-17T16:54:25-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7b27c7cfd569d95e78f85fbcad0161f15343b745",
 "version": "2.0b5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
