
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-18T14:08:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c52cd4af53de29ae81ff9e7dd00b19a28aa14b74",
 "version": "v4.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
