[build-system]
requires = [ "setuptools>=41", "wheel", "versioneer-518" ]
build-backend = "setuptools.build_meta"

# pyproject.toml
[tool.pytest.ini_options]
testpaths = [
    "characterization_ams/unittests",
]
