inherit: "preprocessing.yml"
network:
    name: CustomCNN
    params: {}
optimizer:
    name: "Adam"
    params:
        learning_rate: 0.001
        weight_decay: 0
dataset_transforms:
    - crop:
          max_snp: 400
          max_indiv: null
    - snp_format: concat
    - validate_snp:
          uniform_shape: false
n_epochs: 1
evaluation_interval: 1
batch_size: 8
loader_num_workers: 1
use_cuda: true
cuda_device: null
