# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: error_reason.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='error_reason.proto',
  package='qianlu.qlkit',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x65rror_reason.proto\x12\x0cqianlu.qlkit*\xc8\x04\n\x0b\x45rrorReason\x12\x1c\n\x18\x45RROR_REASON_UNSPECIFIED\x10\x00\x12\x11\n\rPHONE_INVALID\x10\x01\x12\x13\n\x0f\x41UTH_CODE_ERROR\x10\x02\x12\x14\n\x10PASSWORD_INVALID\x10\x03\x12\x12\n\x0ePASSWORD_ERROR\x10\x04\x12\x10\n\x0cPHONE_EXISTS\x10\x05\x12\x15\n\x11\x41UTH_CODE_EXPIRED\x10\x06\x12\x15\n\x11SMS_SERVICE_ERROR\x10\x07\x12\x10\n\x0cUSER_BLOCKED\x10\x08\x12\x11\n\rLOGIN_EXPIRED\x10\t\x12\x12\n\x0eUSER_NOT_FOUND\x10\n\x12\x13\n\x0fPHONE_NOT_FOUND\x10\x0b\x12\x15\n\x11\x41\x44\x44RESS_NOT_FOUND\x10\x0c\x12\x12\n\x0eROOM_NOT_FOUND\x10\x14\x12\r\n\tROOM_LOCK\x10\x15\x12\x1c\n\x18GAME_START_BALANCE_ERROR\x10\x16\x12\x18\n\x14USER_CAN_ACCESS_ROOM\x10\x17\x12\x15\n\x11ROOM_STATUS_ERROR\x10\x18\x12\x14\n\x10START_GAME_ERROR\x10\x19\x12\x0c\n\x08ZJ_ERROR\x10\x1a\x12\x12\n\x0eGAME_NOT_START\x10\x1b\x12\x13\n\x0fGAME_HAS_SETTLE\x10\x1c\x12\x16\n\x12GAME_SETTLED_ERROR\x10\x1d\x12\x11\n\rLOCK_CONFLICT\x10(\x12\x12\n\x0eLOCK_NOT_OWNER\x10)\x12\x16\n\x12\x42\x41LANCE_NOT_ENOUGH\x10*\x12\x0e\n\nLOCK_LIMIT\x10+b\x06proto3'
)

_ERRORREASON = _descriptor.EnumDescriptor(
  name='ErrorReason',
  full_name='qianlu.qlkit.ErrorReason',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR_REASON_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PHONE_INVALID', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTH_CODE_ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PASSWORD_INVALID', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PASSWORD_ERROR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PHONE_EXISTS', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTH_CODE_EXPIRED', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SMS_SERVICE_ERROR', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USER_BLOCKED', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_EXPIRED', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USER_NOT_FOUND', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PHONE_NOT_FOUND', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADDRESS_NOT_FOUND', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROOM_NOT_FOUND', index=13, number=20,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROOM_LOCK', index=14, number=21,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAME_START_BALANCE_ERROR', index=15, number=22,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USER_CAN_ACCESS_ROOM', index=16, number=23,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROOM_STATUS_ERROR', index=17, number=24,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='START_GAME_ERROR', index=18, number=25,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ZJ_ERROR', index=19, number=26,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAME_NOT_START', index=20, number=27,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAME_HAS_SETTLE', index=21, number=28,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAME_SETTLED_ERROR', index=22, number=29,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCK_CONFLICT', index=23, number=40,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCK_NOT_OWNER', index=24, number=41,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BALANCE_NOT_ENOUGH', index=25, number=42,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCK_LIMIT', index=26, number=43,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=37,
  serialized_end=621,
)
_sym_db.RegisterEnumDescriptor(_ERRORREASON)

ErrorReason = enum_type_wrapper.EnumTypeWrapper(_ERRORREASON)
ERROR_REASON_UNSPECIFIED = 0
PHONE_INVALID = 1
AUTH_CODE_ERROR = 2
PASSWORD_INVALID = 3
PASSWORD_ERROR = 4
PHONE_EXISTS = 5
AUTH_CODE_EXPIRED = 6
SMS_SERVICE_ERROR = 7
USER_BLOCKED = 8
LOGIN_EXPIRED = 9
USER_NOT_FOUND = 10
PHONE_NOT_FOUND = 11
ADDRESS_NOT_FOUND = 12
ROOM_NOT_FOUND = 20
ROOM_LOCK = 21
GAME_START_BALANCE_ERROR = 22
USER_CAN_ACCESS_ROOM = 23
ROOM_STATUS_ERROR = 24
START_GAME_ERROR = 25
ZJ_ERROR = 26
GAME_NOT_START = 27
GAME_HAS_SETTLE = 28
GAME_SETTLED_ERROR = 29
LOCK_CONFLICT = 40
LOCK_NOT_OWNER = 41
BALANCE_NOT_ENOUGH = 42
LOCK_LIMIT = 43


DESCRIPTOR.enum_types_by_name['ErrorReason'] = _ERRORREASON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
